// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var busQuery = BusQuery.FromJson(jsonString);

namespace EnrouteAPI
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class BusRouteQuery
    {
        [JsonProperty("errorcode")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Errorcode { get; set; }

        [JsonProperty("errormessage")]
        public string Errormessage { get; set; }

        [JsonProperty("numberofresults")]
        public long Numberofresults { get; set; }

        [JsonProperty("route")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Route { get; set; }

        [JsonProperty("timestamp")]
        public string Timestamp { get; set; }

        [JsonProperty("results")]
        public Result[] Results { get; set; }
    }

    public partial class Result
    {
        [JsonProperty("operatorRoute")]
        public OperatorEnum OperatorRoute { get; set; }

        [JsonProperty("originRoute")]
        public string OriginRoute { get; set; }

        [JsonProperty("originlocalizedRoute")]
        public string OriginlocalizedRoute { get; set; }

        [JsonProperty("destinationRoute")]
        public string DestinationRoute { get; set; }

        [JsonProperty("destinationlocalizedRoute")]
        public string DestinationlocalizedRoute { get; set; }

        [JsonProperty("lastupdated")]
        public string Lastupdated { get; set; }

        [JsonProperty("stops")]
        public Stop[] Stops { get; set; }
    }

    public partial class Stop
    {
        [JsonProperty("stopid")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Stopid { get; set; }

        [JsonProperty("displaystopid")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Displaystopid { get; set; }

        [JsonProperty("shortname")]
        public string Shortname { get; set; }

        [JsonProperty("shortnamelocalized")]
        public string Shortnamelocalized { get; set; }

        [JsonProperty("fullname")]
        public string Fullname { get; set; }

        [JsonProperty("fullnamelocalized")]
        public string Fullnamelocalized { get; set; }

        [JsonProperty("latitude")]
        public string Latitude { get; set; }

        [JsonProperty("longitude")]
        public string Longitude { get; set; }

        [JsonProperty("operators")]
        public OperatorElement[] Operators { get; set; }
    }

    public partial class OperatorElement
    {
        [JsonProperty("name")]
        public OperatorEnum Name { get; set; }

        [JsonProperty("routes")]
        [JsonConverter(typeof(DecodeArrayConverter))]
        public long[] Routes { get; set; }
    }

    public enum OperatorEnum { Bac };

    public partial class BusRouteQuery
    {
        public static BusRouteQuery FromJson(string json) => JsonConvert.DeserializeObject<BusRouteQuery>(json, EnrouteAPI.ConverterRoute.Settings);
    }

    public static class SerializeRoute
    {
        public static string ToJson(this BusRouteQuery self) => JsonConvert.SerializeObject(self, EnrouteAPI.ConverterRoute.Settings);
    }

    internal static class ConverterRoute
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                OperatorEnumConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }

    internal class OperatorEnumConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(OperatorEnum) || t == typeof(OperatorEnum?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "bac")
            {
                return OperatorEnum.Bac;
            }
            throw new Exception("Cannot unmarshal type OperatorEnum");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (OperatorEnum)untypedValue;
            if (value == OperatorEnum.Bac)
            {
                serializer.Serialize(writer, "bac");
                return;
            }
            throw new Exception("Cannot marshal type OperatorEnum");
        }

        public static readonly OperatorEnumConverter Singleton = new OperatorEnumConverter();
    }

    internal class DecodeArrayConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long[]);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            reader.Read();
            var value = new List<long>();
            while (reader.TokenType != JsonToken.EndArray)
            {
                var converter = ParseStringConverter.Singleton;
                var arrayItem = (long)converter.ReadJson(reader, typeof(long), null, serializer);
                value.Add(arrayItem);
                reader.Read();
            }
            return value.ToArray();
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            var value = (long[])untypedValue;
            writer.WriteStartArray();
            foreach (var arrayItem in value)
            {
                var converter = ParseStringConverter.Singleton;
                converter.WriteJson(writer, arrayItem, serializer);
            }
            writer.WriteEndArray();
            return;
        }

        public static readonly DecodeArrayConverter Singleton = new DecodeArrayConverter();
    }
}
